name: 'Release'

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release**

jobs:
  call-release:
    uses: DariuszGarbarz/Tools/.github/workflows/reusable-blenug-release.yml@master
    secrets: inherit